use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn collect_json_files(root: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    let mut stack = vec![root.to_path_buf()];

    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            let ty = entry.file_type()?;
            if ty.is_dir() {
                stack.push(path);
            } else if ty.is_file() && path.extension().is_some_and(|e| e == "json") {
                files.push(path);
            }
        }
    }

    Ok(files)
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let bricks_root = manifest_dir.join("../utils/output");

    println!("cargo:rerun-if-changed={}", bricks_root.display());

    let mut files = collect_json_files(&bricks_root).expect("failed to read ../utils/output");
    files.sort();
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
    }

    let mut out = String::new();
    out.push_str("// @generated by frontend/build.rs\n");
    out.push_str("pub const BRICKS: &[(&str, &str)] = &[\n");

    for file in &files {
        let rel = file
            .strip_prefix(&bricks_root)
            .expect("strip_prefix bricks_root")
            .to_string_lossy()
            .replace('\\', "/");
        let rel_lit = format!("{rel:?}");

        out.push_str("    (");
        out.push_str(&rel_lit);
        out.push_str(
            ", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../utils/output/\", ",
        );
        out.push_str(&rel_lit);
        out.push_str("))),\n");
    }

    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("brick_catalog.rs"), out).expect("write brick_catalog.rs");
}
