import { VerticalBox, TextEdit } from "std-widgets.slint";

export component ContentInput inherits VerticalBox {
    // Properties
    in-out property <string> brick-content;
    
    spacing: 5px;
    preferred-height: 100px;
    max-height: 100px;
    
    Text {
        text: "Brick Content:";
        font-size: 12px;
        font-weight: 700;
    }
    
    TextEdit {
        height: 80px;
        text <=> brick-content;
        placeholder-text: "Enter brick content...";
    }
}
